### ISSUE TITLE
Traditional Chinese is not working properly.

### ISSUE THREAD

**Issue by Lyeuiechang** [peterprd/WhatAboutThis#9]
I've installed the latest version (1.1) on my iPad Air 2, but it seems the Traditional Chinese is not applied properly and still shows English in the About page.

The official code name used in xcode Localizations for Traditional Chinese is zh-Hant, while Simplified Chinese (Chinese) is zh-Hans.

https://stackoverflow.com/questions/46534590/what-language-specifically-is-chinese-language-code-zh

![IMG_0018](https://user-images.githubusercontent.com/26355486/54292056-7f2e9800-45e8-11e9-8db4-ae36e31e7349.JPG)
![IMG_0019](https://user-images.githubusercontent.com/26355486/54292057-7fc72e80-45e8-11e9-9a38-10c24f6a4525.JPG)

Thanks for the great tweak, and I'm not hurry for the fix of this issue. :)

**Comment by thuthuatios** [comment]
You can visit **/Library/Application Support/PeterDev/WhatAboutThis/Localizations.bundle**, rename the **Traditional_Chinese.lproj** folder to **zh-Hant.lproj**. Then respring your device and you will see your language.
Hey @peterprd, it seems this is a misnomer for Localizations.bundle; you should change their name to:

- Arabic.lproj -> **ar.lproj**
- Chinese.lproj -> **zh-Hans.lproj**
- Dutch.lproj -> **nl.lproj**
- English.lproj -> **en.lproj**
- French.lproj -> **fr.lproj**
- German.lproj -> **de.lproj**
- Irish.lproj -> **ga.lproj**
- Japanese.lproj -> **ja.lproj**
- Korean.lproj -> **ko.lproj**
- Traditional_Chinese.lproj -> **zh-Hant.lproj**
- Turkish.lproj -> **tr.lproj**
- Vietnamese.lproj -> **vi.lproj**
